openapi: 3.0.1
info:
  title: Zcash Sandbox Prototype API
  version: "0.1.0"
servers:
  - url: http://localhost:3000
paths:
  /generate_address:
    post:
      summary: Generate a new address
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum: [transparent, shielded]
      responses:
        '200':
          description: address returned
  /faucet:
    post:
      summary: Request faucet to send test ZEC to address
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                amount:
                  type: number
      responses:
        '200':
          description: txid
  /send:
    post:
      summary: Convenience send via node wallet (transparent)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                to:
                  type: string
                amount:
                  type: number
      responses:
        '200':
          description: txid
